baseURL = 'https://drewgrif.github.io/justaguylinux.github.io/'
languageCode = 'en-us'
title = 'JustAGuyLinux'
theme="hugo-ink"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


paginate=3 # articles per page

[params]
	# Optional 64x64 avatar image.
avatar = "https://en.gravatar.com/userimage/235673055/fdc77dbb0949aa8607fec1689aee8bcb?size=64"
subtitle = "NOT AN EXPERT. Just A Guy."
	# Content types to disable Disqus on.
	# disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.


[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://youtube.com/justaguylinux/"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/drewgrif"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/justaguylinux/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/jaglinux.github.io/index.xml"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


